### ISSUE TITLE
Update Event Title to show names

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/schedul8r#36]
As a hiring team member.   
I want to see the names of the interviewee and interviewer on the Google Calendar event title.   
So that I don't have to look at the description.  

### Acceptance criteria
Should look something like this.   
<img width="180" alt="Screenshot 2023-09-07 at 2 16 39 PM" src="https://github.com/rise8-us/schedul8r/assets/122058530/ed4134ba-9125-4c1c-b549-38f91580a40b">

**Comment by brijal-rise8** [comment]
The Meeting title has been updated , tested, confirmed pushed to the production.
