### ISSUE TITLE
Improve build config

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/schedul8r#6]
**As a** dev. 
**I want** both the appscript.json file, `backend`, and `frontend` dirs to be in src, and copied to `dist` on `npm run build`.  
**So that** there is proper order and automation  

# Acceptance criteria
`dist` will be emptied and all new code will be entered in `dist` as part of the build process

**Comment by dlamberson-rise8** [comment]
This is done

**Comment by jwills-r8** [comment]
Looks good, I think at some point in the future I'd like to figure out if we can use vite to build the backend into a single file as well
