### ISSUE TITLE
Repo tidyness

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/schedul8r#7]
**As a** dev  
**I want** repo rules configured, git hooks established, lint and code standards defined.  
**So that** the code can always comply with the ilities of good engineering.  

# Acceptance criteria
@jwills-r8, @jmiller-rise8, or @dlamberson-rise8  feel as though they have reached a zen state of peace when reading through the code

**Comment by dlamberson-rise8** [comment]
added eslint w/ a config. Ran the linter.
